"""initial schema

Revision ID: 853b1b696474
Revises:
Create Date: 2026-08-19 19:31:13.748951

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '853b1b696474'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_organization_id'), 'store', ['organization_id'], unique=False)
    op.create_table('api_key',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('store_id', sa.String(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_key_key_hash'), 'api_key', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_key_store_id'), 'api_key', ['store_id'], unique=False)
    op.create_table('camera',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('store_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camera_store_id'), 'camera', ['store_id'], unique=False)
    op.create_table('pos_transaction',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('store_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'order_id', name='uq_pos_transaction_store_order_id')
    )
    op.create_index(op.f('ix_pos_transaction_order_id'), 'pos_transaction', ['order_id'], unique=False)
    op.create_index(op.f('ix_pos_transaction_store_id'), 'pos_transaction', ['store_id'], unique=False)
    op.create_index(op.f('ix_pos_transaction_timestamp'), 'pos_transaction', ['timestamp'], unique=False)
    op.create_table('tracked_entity',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('store_id', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('age_bucket', sa.String(), nullable=True),
    sa.Column('is_staff', sa.Boolean(), nullable=True),
    sa.Column('staff_confidence_score', sa.Float(), nullable=True),
    sa.Column('staff_inference_reason', sa.String(), nullable=True),
    sa.Column('group_id', sa.String(), nullable=True),
    sa.Column('group_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracked_entity_store_id'), 'tracked_entity', ['store_id'], unique=False)
    op.create_table('zone',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('store_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('SHELF', 'DISPLAY', 'CHECKOUT', 'ENTRY_DOOR', 'OTHER', name='zonetype'), nullable=False),
    sa.Column('is_revenue_zone', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zone_store_id'), 'zone', ['store_id'], unique=False)
    op.create_table('identity_alias',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tracked_entity_id', sa.String(), nullable=False),
    sa.Column('store_id', sa.String(), nullable=False),
    sa.Column('camera_id', sa.String(), nullable=False),
    sa.Column('source_field', sa.String(), nullable=False),
    sa.Column('source_value', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.ForeignKeyConstraint(['tracked_entity_id'], ['tracked_entity.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'camera_id', 'source_field', 'source_value', name='uq_identity_alias_scope')
    )
    op.create_index(op.f('ix_identity_alias_store_id'), 'identity_alias', ['store_id'], unique=False)
    op.create_index(op.f('ix_identity_alias_tracked_entity_id'), 'identity_alias', ['tracked_entity_id'], unique=False)
    op.create_table('pos_transaction_item',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('brand_name', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['pos_transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pos_transaction_item_transaction_id'), 'pos_transaction_item', ['transaction_id'], unique=False)
    op.create_table('visit_session',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tracked_entity_id', sa.String(), nullable=False),
    sa.Column('store_id', sa.String(), nullable=False),
    sa.Column('entry_time', sa.DateTime(), nullable=False),
    sa.Column('exit_time', sa.DateTime(), nullable=True),
    sa.Column('dwell_seconds', sa.Integer(), nullable=True),
    sa.Column('session_status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'ORPHANED', name='sessionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.ForeignKeyConstraint(['tracked_entity_id'], ['tracked_entity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visit_session_store_id'), 'visit_session', ['store_id'], unique=False)
    op.create_index(op.f('ix_visit_session_tracked_entity_id'), 'visit_session', ['tracked_entity_id'], unique=False)
    op.create_table('event',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_event_id', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('tracked_entity_id', sa.String(), nullable=False),
    sa.Column('store_id', sa.String(), nullable=False),
    sa.Column('camera_id', sa.String(), nullable=True),
    sa.Column('zone_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.Enum('ENTRY', 'EXIT', 'ZONE_ENTERED', 'ZONE_EXITED', 'ZONE_DWELL', 'BILLING_QUEUE_JOIN', 'QUEUE_COMPLETED', 'QUEUE_ABANDONED', 'REENTRY', name='eventtype'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('hotspot_x', sa.Float(), nullable=True),
    sa.Column('hotspot_y', sa.Float(), nullable=True),
    sa.Column('is_face_hidden', sa.Boolean(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('queue_event_id', sa.String(), nullable=True),
    sa.Column('queue_join_ts', sa.DateTime(), nullable=True),
    sa.Column('queue_served_ts', sa.DateTime(), nullable=True),
    sa.Column('queue_exit_ts', sa.DateTime(), nullable=True),
    sa.Column('wait_seconds', sa.Integer(), nullable=True),
    sa.Column('queue_position_at_join', sa.Integer(), nullable=True),
    sa.Column('abandoned', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['camera.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['visit_session.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.ForeignKeyConstraint(['tracked_entity_id'], ['tracked_entity.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zone.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'source_event_id', name='uq_event_store_source_event_id')
    )
    op.create_index(op.f('ix_event_event_type'), 'event', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_queue_event_id'), 'event', ['queue_event_id'], unique=False)
    op.create_index(op.f('ix_event_session_id'), 'event', ['session_id'], unique=False)
    op.create_index(op.f('ix_event_source_event_id'), 'event', ['source_event_id'], unique=False)
    op.create_index(op.f('ix_event_store_id'), 'event', ['store_id'], unique=False)
    op.create_index(op.f('ix_event_timestamp'), 'event', ['timestamp'], unique=False)
    op.create_index(op.f('ix_event_tracked_entity_id'), 'event', ['tracked_entity_id'], unique=False)
    op.create_table('transaction_correlation',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('MATCHED', 'UNMATCHED', 'AMBIGUOUS', name='correlationstatus'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('correlation_method', sa.String(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['visit_session.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['pos_transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_correlation_session_id'), 'transaction_correlation', ['session_id'], unique=False)
    op.create_index(op.f('ix_transaction_correlation_status'), 'transaction_correlation', ['status'], unique=False)
    op.create_index(op.f('ix_transaction_correlation_transaction_id'), 'transaction_correlation', ['transaction_id'], unique=False)
    op.create_table('raw_event',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_event_id', sa.String(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('validation_status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_event_event_id'), 'raw_event', ['event_id'], unique=False)
    op.create_index(op.f('ix_raw_event_source'), 'raw_event', ['source'], unique=False)
    op.create_index(op.f('ix_raw_event_source_event_id'), 'raw_event', ['source_event_id'], unique=False)
    op.create_index(op.f('ix_raw_event_validation_status'), 'raw_event', ['validation_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_event_validation_status'), table_name='raw_event')
    op.drop_index(op.f('ix_raw_event_source_event_id'), table_name='raw_event')
    op.drop_index(op.f('ix_raw_event_source'), table_name='raw_event')
    op.drop_index(op.f('ix_raw_event_event_id'), table_name='raw_event')
    op.drop_table('raw_event')
    op.drop_index(op.f('ix_transaction_correlation_transaction_id'), table_name='transaction_correlation')
    op.drop_index(op.f('ix_transaction_correlation_status'), table_name='transaction_correlation')
    op.drop_index(op.f('ix_transaction_correlation_session_id'), table_name='transaction_correlation')
    op.drop_table('transaction_correlation')
    op.drop_index(op.f('ix_event_tracked_entity_id'), table_name='event')
    op.drop_index(op.f('ix_event_timestamp'), table_name='event')
    op.drop_index(op.f('ix_event_store_id'), table_name='event')
    op.drop_index(op.f('ix_event_source_event_id'), table_name='event')
    op.drop_index(op.f('ix_event_session_id'), table_name='event')
    op.drop_index(op.f('ix_event_queue_event_id'), table_name='event')
    op.drop_index(op.f('ix_event_event_type'), table_name='event')
    op.drop_table('event')
    op.drop_index(op.f('ix_visit_session_tracked_entity_id'), table_name='visit_session')
    op.drop_index(op.f('ix_visit_session_store_id'), table_name='visit_session')
    op.drop_table('visit_session')
    op.drop_index(op.f('ix_pos_transaction_item_transaction_id'), table_name='pos_transaction_item')
    op.drop_table('pos_transaction_item')
    op.drop_index(op.f('ix_identity_alias_tracked_entity_id'), table_name='identity_alias')
    op.drop_index(op.f('ix_identity_alias_store_id'), table_name='identity_alias')
    op.drop_table('identity_alias')
    op.drop_index(op.f('ix_zone_store_id'), table_name='zone')
    op.drop_table('zone')
    op.drop_index(op.f('ix_tracked_entity_store_id'), table_name='tracked_entity')
    op.drop_table('tracked_entity')
    op.drop_index(op.f('ix_pos_transaction_timestamp'), table_name='pos_transaction')
    op.drop_index(op.f('ix_pos_transaction_store_id'), table_name='pos_transaction')
    op.drop_index(op.f('ix_pos_transaction_order_id'), table_name='pos_transaction')
    op.drop_table('pos_transaction')
    op.drop_index(op.f('ix_camera_store_id'), table_name='camera')
    op.drop_table('camera')
    op.drop_index(op.f('ix_api_key_store_id'), table_name='api_key')
    op.drop_index(op.f('ix_api_key_key_hash'), table_name='api_key')
    op.drop_table('api_key')
    op.drop_index(op.f('ix_store_organization_id'), table_name='store')
    op.drop_table('store')
    op.drop_table('organization')
    # ### end Alembic commands ###
