from __future__ import annotations

import hashlib
import secrets

from fastapi import Depends, Header, HTTPException, status
from sqlalchemy import select
from sqlalchemy.orm import Session

from app.db.session import get_db
from app.models.auth import ApiKey

API_KEY_HEADER = "X-API-Key"


def generate_api_key() -> str:
    """Return a new high-entropy raw API key. Callers must store it themselves --
    only its hash is ever persisted, so it cannot be recovered later."""
    return secrets.token_urlsafe(32)


def hash_api_key(raw_key: str) -> str:
    """Hash a raw API key for storage/lookup.

    SHA-256 is appropriate here (rather than a slow password hash like bcrypt)
    because API keys are high-entropy random tokens generated by us, not
    low-entropy secrets chosen by a user -- there is no brute-force risk a slow
    hash would meaningfully mitigate, and it avoids adding a new dependency.
    """
    return hashlib.sha256(raw_key.encode("utf-8")).hexdigest()


def create_api_key(db: Session, store_id: str) -> tuple[ApiKey, str]:
    """Create and persist a new API key for a store.

    Returns the persisted row and the raw key. The raw key is only ever available
    at this moment -- the caller (an admin script/endpoint) is responsible for
    delivering it to whoever owns the store's ingestion pipeline.
    """
    raw_key = generate_api_key()
    api_key = ApiKey(store_id=store_id, key_hash=hash_api_key(raw_key))
    db.add(api_key)
    db.flush()
    return api_key, raw_key


def require_api_key(
    x_api_key: str | None = Header(default=None, alias=API_KEY_HEADER),
    db: Session = Depends(get_db),
) -> ApiKey:
    """FastAPI dependency: require a valid, active API key on the X-API-Key header.

    Applied to event ingestion routes for P1. Dashboard/analytics read routes are
    intentionally left open in this phase -- gating them requires the User +
    StoreAccess/RBAC model, which is scoped to P2 so this stays modular rather than
    a throwaway gate that P2 has to rip out.
    """
    if not x_api_key:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="API key is required.")

    api_key = db.execute(
        select(ApiKey).where(ApiKey.key_hash == hash_api_key(x_api_key), ApiKey.is_active.is_(True))
    ).scalar_one_or_none()

    if api_key is None:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="API key is invalid or inactive.")

    return api_key
